on:
  push:
    branches-ignore:
      - website
      - gh-pages
  pull_request:
    branches-ignore:
      - website
      - gh-pages

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Tree
        uses: actions/checkout@v3

      - name: Build container image
        run: |
          docker build -t halo .

      - name: Build
        run: |
          docker run --rm  -u $(id -u):$(id -g) -v $PWD:/work -w /work halo make -C src
